/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/molecules/Buttons/ActionButton.vue')['default']
    AppHeader: typeof import('./src/components/organisms/AppHeader/AppHeader.vue')['default']
    BasicBox: typeof import('./src/components/atoms/BasicBox/BasicBox.vue')['default']
    BasicModal: typeof import('./src/components/atoms/BasicModal/BasicModal.vue')['default']
    CenteredBox: typeof import('./src/components/molecules/CenteredBox/CenteredBox.vue')['default']
    CenteredModal: typeof import('./src/components/organisms/CenteredModal/CenteredModal.vue')['default']
    ExerciseForm: typeof import('./src/components/modals/WorkoutModal/ExerciseForm.vue')['default']
    FullscreenLoader: typeof import('./src/components/molecules/FullscreenLoader/FullscreenLoader.vue')['default']
    HeadlineL: typeof import('./src/components/atoms/Typography/HeadlineL.vue')['default']
    HeadlineM: typeof import('./src/components/atoms/Typography/HeadlineM.vue')['default']
    HeadlineS: typeof import('./src/components/atoms/Typography/HeadlineS.vue')['default']
    HeadlineXL: typeof import('./src/components/atoms/Typography/HeadlineXL.vue')['default']
    HeadlineXS: typeof import('./src/components/atoms/Typography/HeadlineXS.vue')['default']
    IconButton: typeof import('./src/components/atoms/Buttons/IconButton.vue')['default']
    LoginModal: typeof import('./src/components/modals/LoginModal/LoginModal.vue')['default']
    NavigationMenu: typeof import('./src/components/organisms/NavigationMenu/NavigationMenu.vue')['default']
    ProgressCircular: typeof import('./src/components/atoms/ProgressCircular/ProgressCircular.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextAreaWithValidation: typeof import('./src/components/atoms/TextAreaWithValidation/TextAreaWithValidation.vue')['default']
    TextBody: typeof import('./src/components/atoms/Typography/TextBody.vue')['default']
    TextButton: typeof import('./src/components/atoms/Buttons/TextButton.vue')['default']
    TextButtonWithIcon: typeof import('./src/components/atoms/Buttons/TextButtonWithIcon.vue')['default']
    TextCaption: typeof import('./src/components/atoms/Typography/TextCaption.vue')['default']
    TextField: typeof import('./src/components/atoms/TextField/TextField.vue')['default']
    TextFieldWithValidation: typeof import('./src/components/atoms/TextFieldWithValidation/TextFieldWithValidation.vue')['default']
    TextSubtitle: typeof import('./src/components/atoms/Typography/TextSubtitle.vue')['default']
    ToastAlert: typeof import('./src/components/atoms/ToastAlert/ToastAlert.vue')['default']
    TrainersListVirtualScroll: typeof import('./src/components/organisms/UserListVirtualScroll/TrainersListVirtualScroll.vue')['default']
    UserListItem: typeof import('./src/components/molecules/UserListItem/UserListItem.vue')['default']
    UserListVirtualScroll: typeof import('./src/components/organisms/UserListVirtualScroll/UserListVirtualScroll.vue')['default']
    WorkoutModal: typeof import('./src/components/modals/WorkoutModal/WorkoutModal.vue')['default']
    WorkoutModaltemp: typeof import('./src/components/modals/WorkoutModal/WorkoutModaltemp.vue')['default']
  }
}
