/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Body: typeof import('./src/components/atoms/Typography/Body.vue')['default']
    Button: typeof import('./src/components/atoms/Buttons/Button.vue')['default']
    Caption: typeof import('./src/components/atoms/Typography/Caption.vue')['default']
    Header: typeof import('./src/components/organisms/Header/Header.vue')['default']
    HeadlineL: typeof import('./src/components/atoms/Typography/HeadlineL.vue')['default']
    HeadlineM: typeof import('./src/components/atoms/Typography/HeadlineM.vue')['default']
    HeadlineS: typeof import('./src/components/atoms/Typography/HeadlineS.vue')['default']
    HeadlineXL: typeof import('./src/components/atoms/Typography/HeadlineXL.vue')['default']
    HeadlineXS: typeof import('./src/components/atoms/Typography/HeadlineXS.vue')['default']
    IconButton: typeof import('./src/components/atoms/Buttons/IconButton.vue')['default']
    Menu: typeof import('./src/components/organisms/Menu/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subtitle: typeof import('./src/components/atoms/Typography/Subtitle.vue')['default']
  }
}
