name: Build and deploy container app to Azure Web App - team-project-a

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: teamprojectacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t teamprojectacr.azurecr.io/projecta:${{ github.sha }}
          docker push teamprojectacr.azurecr.io/projecta:${{ github.sha }}
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'project-a-team'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'mycontainer.azurecr.io/projecta:${{ github.sha }}'