name: pull-request-test
on:
  pull_request:
    branches: [ master ]
jobs:
  test-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Build docker image
        run: docker build . -t test_image
  lint-and-build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Go to frontend directory
    - run: cd src/TeamProjectA.Web
    - name: Install modules
    - run: npm install
    - name: Run ESLint
    - run: eslint --ext .vue src
    - name: Build app
    - run: npm run build
     
